#:mute

#:include '../src/common.fypp'

#:set PROGRAM_NAME = 'check_p_n_at_endpoints'

#:def GENERATE_SUBROUTINE_NAME(data_type, real_kind)
${PROGRAM_NAME}$_${data_type}$${str(real_kind)}$
#:enddef GENERATE_SUBROUTINE_NAME

#:endmute
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  use, intrinsic :: iso_fortran_env, only: int32
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_exceptions, only: ieee_inexact
  use, intrinsic :: ieee_exceptions, only: ieee_set_halting_mode

  use, non_intrinsic :: ${MODULE_NAME}$, only: ${P_N_SELECTABLE_INTERFACE}$

  use, non_intrinsic :: test_utilities, only: is_equal



  implicit none



  integer(int32), parameter :: minval_degree = 0
  #:for DATA_TYPE in DATA_TYPES

  #:for REAL_KIND in REAL_KINDS
  #:if DATA_TYPE == 'complex'
  ${DATA_TYPE}$(real${REAL_KIND}$), parameter :: one_${DATA_TYPE}$${REAL_KIND}$ = cmplx(1.0_real${REAL_KIND}$, 0.0_real${REAL_KIND}$, real${REAL_KIND}$)
  #:elif DATA_TYPE == 'real'
  ${DATA_TYPE}$(real${REAL_KIND}$), parameter :: one_${DATA_TYPE}$${REAL_KIND}$ = 1.0_real${REAL_KIND}$
  #:endif
  #:endfor
  #:endfor



  call ieee_set_halting_mode(ieee_inexact, .true.)
  #:for DATA_TYPE in DATA_TYPES

  #:for REAL_KIND in REAL_KINDS
  call ${GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)}$()
  #:endfor
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)
  subroutine ${SUBROUTINE_NAME}$()

    integer(int32), parameter :: maxval_degree = ${MAXVAL_DEGREE_REAL(REAL_KIND)}$


    integer :: degree

    ${DATA_TYPE}$(real${REAL_KIND}$) :: actual_${P_N_SELECTABLE_INTERFACE}$


    plus_one: do degree = minval_degree, maxval_degree

      actual_${P_N_SELECTABLE_INTERFACE}$ = ${P_N_SELECTABLE_INTERFACE}$(degree, one_${DATA_TYPE}$${REAL_KIND}$)

      if ( is_equal(actual_${P_N_SELECTABLE_INTERFACE}$, one_${DATA_TYPE}$${REAL_KIND}$) ) cycle

      write( error_unit, '(A,I0,A,1X)', advance='no' ) 'p_{', degree, '} (x=1.0) was'
      write( error_unit, *                           ) actual_${P_N_SELECTABLE_INTERFACE}$
      write( error_unit, *                           ) 'p_{', degree, '} (x=1.0) must be', one_${DATA_TYPE}$${REAL_KIND}$

      error stop

    end do plus_one


    minus_one: block

      ${DATA_TYPE}$(real${REAL_KIND}$) :: expected_${P_N_SELECTABLE_INTERFACE}$


      expected_${P_N_SELECTABLE_INTERFACE}$ = - one_${DATA_TYPE}$${REAL_KIND}$ ! initialization (the minval_degree must be even)


      do degree = minval_degree, maxval_degree

        expected_${P_N_SELECTABLE_INTERFACE}$ = - expected_${P_N_SELECTABLE_INTERFACE}$
        actual_${P_N_SELECTABLE_INTERFACE}$   = ${P_N_SELECTABLE_INTERFACE}$( degree, (- one_${DATA_TYPE}$${REAL_KIND}$) )

        if ( is_equal(actual_${P_N_SELECTABLE_INTERFACE}$, expected_${P_N_SELECTABLE_INTERFACE}$) ) cycle

        write( error_unit, '(A,I0,A,1X)', advance='no' ) 'p_{', degree, '} (x=-1.0) was'
        write( error_unit, *                           ) actual_${P_N_SELECTABLE_INTERFACE}$
        write( error_unit, *                           ) 'p_{', degree, '} (x=-1.0) must be', expected_${P_N_SELECTABLE_INTERFACE}$

        error stop

      end do

    end block minus_one

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE
end program ${PROGRAM_NAME}$
