#:mute

#:include '../src/common.fypp'

#:set PROGRAM_NAME = 'check_p_n_invalid_degree'

#:def GENERATE_SUBROUTINE_NAME(real_kind)
${PROGRAM_NAME}$_real${str(real_kind)}$
#:enddef GENERATE_SUBROUTINE_NAME

#:endmute
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  use, intrinsic :: iso_fortran_env, only: int32
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_is_nan

  use, non_intrinsic :: ${MODULE_NAME}$, only: ${P_N_SELECTABLE_INTERFACE}$



  implicit none



  #:for REAL_KIND in REAL_KINDS
  call ${GENERATE_SUBROUTINE_NAME(REAL_KIND)}$()
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = GENERATE_SUBROUTINE_NAME(REAL_KIND)
  subroutine ${SUBROUTINE_NAME}$()

    integer(int32), parameter :: maxval_degree = ${MAXVAL_DEGREE_REAL(REAL_KIND)}$


    integer :: degree

    real(real${REAL_KIND}$) :: actual_${P_N_SELECTABLE_INTERFACE}$, x


    do degree = (-10_int32 * maxval_degree), (10_int32 * maxval_degree)

      select case (degree)

        case (0_int32:maxval_degree)

          cycle

        case default

          call random_number(x)

          actual_${P_N_SELECTABLE_INTERFACE}$ = ${P_N_SELECTABLE_INTERFACE}$(degree, x)

          if ( .not. ieee_is_nan(actual_${P_N_SELECTABLE_INTERFACE}$) ) then

            write(error_unit, *) 'n, x   : ', degree, ',', x
            write(error_unit, *) 'p_n(x) : ', actual_${P_N_SELECTABLE_INTERFACE}$
            write(error_unit, *) 'This value must be NaN.'

            error stop

          end if

      end select

    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
  #! REAL_KIND
end program ${PROGRAM_NAME}$
