#:mute

#:include '../src/common.fypp'

#:set PROGRAM_NAME = 'check_p_n_matches_p_nn'

#:def GENERATE_SUBROUTINE_NAME(data_type, real_kind)
${PROGRAM_NAME}$_${data_type}$${str(real_kind)}$
#:enddef GENERATE_SUBROUTINE_NAME

#:endmute
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: error_unit
  use, intrinsic :: iso_fortran_env, only: int32
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, non_intrinsic :: ${MODULE_NAME}$

  use, non_intrinsic :: test_utilities, only: is_equal



  implicit none



  integer, parameter :: num_trials = 100


  #:for DATA_TYPE in DATA_TYPES

  #:for REAL_KIND in REAL_KINDS
  call ${GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)}$()
  #:endfor
  #:endfor

  print *, 'OK: ${PROGRAM_NAME}$'



  contains


  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)
  subroutine ${SUBROUTINE_NAME}$()

    integer :: i_trial

    #:if DATA_TYPE == 'complex'
    real(real${REAL_KIND}$) :: tmp

    complex(real${REAL_KIND}$) :: x
    #:elif DATA_TYPE == 'real'
    real(real${REAL_KIND}$) :: x
    #:endif


    do i_trial = 1, num_trials

      #:if DATA_TYPE == 'complex'
      do

        call random_number(tmp); x%re = 2.0_real${REAL_KIND}$ * tmp - 1.0_real${REAL_KIND}$
        call random_number(tmp); x%im = 2.0_real${REAL_KIND}$ * tmp - 1.0_real${REAL_KIND}$

        if ( abs(x) .le. 1.0_real${REAL_KIND}$ ) exit

      end do
      #:elif DATA_TYPE == 'real'
      call random_number(x) ! [0, 1)

      x = 2.0_real${REAL_KIND}$ * x - 1.0_real${REAL_KIND}$ ! [-1, 1)
      #:endif

      #:for DEGREE in range( 0, (MAXVAL_DEGREE_REAL(REAL_KIND) + 1) )

      call check_equality_${DATA_TYPE}$${str(REAL_KIND)}$( &!
        degree = ${DEGREE}$_int32, &!
        x      = x , &!
        function_${P_N_SELECTABLE_INTERFACE}$  = ${P_N_INTERFACE(DEGREE)}$(x), &!
        interface_${P_N_SELECTABLE_INTERFACE}$ = ${P_N_SELECTABLE_INTERFACE}$(${DEGREE}$_int32, x) &!
      )

      #:endfor
    end do

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE

  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = 'check_equality_' + DATA_TYPE + str(REAL_KIND)
  subroutine ${SUBROUTINE_NAME}$(degree, x, function_${P_N_SELECTABLE_INTERFACE}$, interface_${P_N_SELECTABLE_INTERFACE}$)

    integer(int32), intent(in) :: degree

    ${DATA_TYPE}$(real${REAL_KIND}$), intent(in) :: x, function_${P_N_SELECTABLE_INTERFACE}$, interface_${P_N_SELECTABLE_INTERFACE}$


    if ( is_equal(function_${P_N_SELECTABLE_INTERFACE}$, interface_${P_N_SELECTABLE_INTERFACE}$) ) return


    write(error_unit, *) 'degree, x : ', degree, ',', x
    write(error_unit, *) 'function  : ', function_${P_N_SELECTABLE_INTERFACE}$
    write(error_unit, *) 'interface : ', interface_${P_N_SELECTABLE_INTERFACE}$
    write(error_unit, *) 'These are must be equal.'

    error stop

  end subroutine ${SUBROUTINE_NAME}$
  #:del SUBROUTINE_NAME

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE
end program ${PROGRAM_NAME}$
