#:mute

#:include '../src/common.fypp'
#:set TEST_MODULE_NAME = 'test_utilities'

#:def INTERFACE_BLOCK(interface_name)
  interface ${interface_name}$
  #:for REAL_KIND in REAL_KINDS
    module procedure :: ${interface_name}$_real${REAL_KIND}$
  #:endfor
  end interface ${interface_name}$
#:enddef

#:endmute
module ${TEST_MODULE_NAME}$

  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: operator(.eq.)
  use, intrinsic :: ieee_arithmetic, only: ieee_class
  use, intrinsic :: ieee_arithmetic, only: ieee_class_type
  use, intrinsic :: ieee_arithmetic, only: ieee_negative_zero
  use, intrinsic :: ieee_arithmetic, only: ieee_positive_zero



  implicit none



  private

  public :: is_zero



  @:INTERFACE_BLOCK(is_zero)


  contains



  #:set FUNCTION_NAME = 'is_zero_class'
  logical pure function ${FUNCTION_NAME}$(class)

    type(ieee_class_type), intent(in) :: class

    ${FUNCTION_NAME}$ = &!
      (class .eq. ieee_positive_zero) .or. &!
      (class .eq. ieee_negative_zero)

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = 'is_zero_real' + str(REAL_KIND)
  logical pure function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x

    ${FUNCTION_NAME}$ = is_zero_class( ieee_class(x) )

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
end module ${TEST_MODULE_NAME}$
