#:mute

#:include '../src/common.fypp'
#:set TEST_MODULE_NAME = 'test_utilities'

#:def COMMENT_IS_EQUAL()
    !! @warning
    !! `a - b` must be finite
    !! @endwarning
#:enddef

#:def INTERFACE_BLOCK(interface_name)
  interface ${interface_name}$
  #:if interface_name == 'is_equal'
    @:COMMENT_IS_EQUAL()

  #:endif
  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS
    module procedure :: ${interface_name}$_${DATA_TYPE}$${REAL_KIND}$
  #:endfor
  #:endfor
  #:if interface_name == 'is_equal'

  #:endif
  end interface ${interface_name}$
#:enddef

#:endmute
module ${TEST_MODULE_NAME}$

  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: operator(.eq.)
  use, intrinsic :: ieee_arithmetic, only: ieee_class
  use, intrinsic :: ieee_arithmetic, only: ieee_class_type
  use, intrinsic :: ieee_arithmetic, only: ieee_negative_zero
  use, intrinsic :: ieee_arithmetic, only: ieee_positive_zero



  implicit none



  private

  public :: is_equal
  public :: is_zero



  @:INTERFACE_BLOCK(is_equal)

  @:INTERFACE_BLOCK(is_zero)



  contains



  #:set FUNCTION_NAME = 'is_zero_class'
  logical pure function ${FUNCTION_NAME}$(class)

    type(ieee_class_type), intent(in) :: class

    ${FUNCTION_NAME}$ = &!
      (class .eq. ieee_positive_zero) .or. &!
      (class .eq. ieee_negative_zero)

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = 'is_zero_' + DATA_TYPE + str(REAL_KIND)
  logical pure function ${FUNCTION_NAME}$(x)

    ${DATA_TYPE}$(real${REAL_KIND}$), intent(in) :: x

    #:if DATA_TYPE == 'complex'
    ${FUNCTION_NAME}$ = is_zero(x%re) .and. is_zero(x%im)
    #:elif DATA_TYPE == 'real'
    ${FUNCTION_NAME}$ = is_zero_class( ieee_class(x) )
    #:endif

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE

  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = 'is_equal_' + DATA_TYPE + str(REAL_KIND)
  logical pure function ${FUNCTION_NAME}$(a, b)
    @:COMMENT_IS_EQUAL()

    ${DATA_TYPE}$(real${REAL_KIND}$), intent(in) :: a, b

    ${FUNCTION_NAME}$ = is_zero(a - b)

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE
end module ${TEST_MODULE_NAME}$
