#:mute

#:include '../src/common.fypp'

#:endmute
reset session

set size square
set xzeroaxis linetype -1
set yzeroaxis linetype -1
set palette model RGB rgbformulae 35,13,10 #rainbow (blue-green-yellow-red)
set xlabel 'real(z)'
set ylabel 'imag(z)'
set xrange [-1.1:1.1]
set yrange [-1.1:1.1]
set cbtics 1

set terminal svg dynamic

#:for REAL_KIND in REAL_KINDS

set title ('precision: REAL' . ${REAL_KIND}$)

do for [degree = 0:${MAXVAL_DEGREE_REAL(REAL_KIND)}$] {

    set cblabel sprintf('log10[ abs( P_{%d}(z) ) ]', degree)

    set output sprintf("example/demo_p_%2.2d_complex${REAL_KIND}$_actual.svg", degree)

    plot 'example/demo_p_n_complex${REAL_KIND}$_actual.dat' \
         using 1:2:( log10( column(degree + 3) ) ) \
         with points \
         pointtype 7 pointsize 0.5 linecolor palette \
         notitle



    set output sprintf("example/demo_p_%2.2d_complex${REAL_KIND}$_error.svg", degree)

    set cblabel sprintf('log10[ abs( P_{%d}(z) vs scipy ) ]', degree)

    plot 'example/demo_p_n_complex${REAL_KIND}$_error.dat' \
         using 1:2:( log10( column(degree + 3) ) ) \
         with points \
         pointtype 7 pointsize 0.5 linecolor palette \
         notitle

}

#:endfor

set output
