#:mute

#:include '../src/common.fypp'

#:endmute
reset session

set xlabel 'x'

set xrange [-1.1:1.1]
set cbrange [0:${MAXVAL_DEGREE_INT64}$]

set xzeroaxis

set key outside

set palette model RGB rgbformulae 35,13,10 #rainbow (blue-green-yellow-red)
unset colorbox

set terminal svg dynamic

#:for REAL_KIND in REAL_KINDS

set title ('precision: REAL' . ${REAL_KIND}$)

set output  ('example/demo_p_n_real${REAL_KIND}$_actual.svg')
set yrange [-1.1:1.1]
set ylabel 'p_n (x)'

plot for [degree = 0:${MAXVAL_DEGREE_REAL(REAL_KIND)}$] \
     'example/demo_p_n_real${REAL_KIND}$_actual.dat' \
     using 1:(column(degree + 2)):(degree) \
     with lines \
     linewidth 0.5 linecolor palette title sprintf("p_{%d}", degree)

set output  ('example/demo_p_n_real${REAL_KIND}$_error.svg')
unset yrange
set ylabel 'log10(abs error vs scipy)'

plot for [degree = 0:${MAXVAL_DEGREE_REAL(REAL_KIND)}$] \
     'example/demo_p_n_real${REAL_KIND}$_error.dat' \
     using 1:( log10( abs( column(degree + 2) ) ) ):(degree) \
     with lines \
     linewidth 0.5 linecolor palette title sprintf("p_{%d}", degree)

#:endfor

set output
