#:mute

#:include '../src/common.fypp'

#:set PROGRAM_NAME = 'demo_p_n'

#:def GENERATE_SUBROUTINE_NAME(data_type, real_kind)
${PROGRAM_NAME}$_${data_type}$${str(real_kind)}$
#:enddef GENERATE_SUBROUTINE_NAME

#:endmute
program ${PROGRAM_NAME}$

  use, intrinsic :: iso_fortran_env, only: int32
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, non_intrinsic :: ${MODULE_NAME}$, only: ${P_N_SELECTABLE_INTERFACE}$



  implicit none



  integer(int32), parameter :: minval_degree = 0

  integer(int32), parameter :: maxval_degree_interface = ${MAXVAL_DEGREE_INTERFACE}$
  #:for DATA_TYPE in DATA_TYPES

  character(*), parameter :: ref_file_${DATA_TYPE}$ = 'example/scipy_${DATA_TYPE}$.dat'
  #:endfor


  #:for DATA_TYPE in DATA_TYPES

  #:for REAL_KIND in REAL_KINDS
  call ${GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)}$()
  #:endfor
  #:endfor

  print *, 'Finish: ${PROGRAM_NAME}$'



  contains

  #:for DATA_TYPE in DATA_TYPES

  #:for REAL_KIND in REAL_KINDS

  #:set SUBROUTINE_NAME = GENERATE_SUBROUTINE_NAME(DATA_TYPE, REAL_KIND)
  subroutine ${SUBROUTINE_NAME}$

    integer(int32), parameter :: maxval_degree = ${MAXVAL_DEGREE_REAL(REAL_KIND)}$


    integer(int32) :: degree

    integer(int32), parameter :: &!
      list_degree(minval_degree:maxval_degree) = &!
        [( degree, degree = minval_degree, maxval_degree )]


    integer :: iostat

    integer :: ref_unit, save_unit_actual, save_unit_error

    ${DATA_TYPE}$(real${REAL_KIND}$) :: x

    ${DATA_TYPE}$(real${REAL_KIND}$) :: actual_${P_N_SELECTABLE_INTERFACE}$(minval_degree:maxval_degree)

    ${DATA_TYPE}$(real${REAL_KIND}$) :: error_${P_N_SELECTABLE_INTERFACE}$(minval_degree:maxval_degree)

    ${DATA_TYPE}$(real${REAL_KIND}$) :: scipy_${P_N_SELECTABLE_INTERFACE}$(minval_degree:maxval_degree_interface)


    open( &!
      newunit = ref_unit, &!
      file    = ref_file_${DATA_TYPE}$, &!
      action  = 'read', &!
      form    = 'formatted', &!
      status  = 'old' &!
    )

    open( &!
      newunit = save_unit_actual , &!
      file    = 'example/${SUBROUTINE_NAME}$_actual.dat' , &!
      action  = 'write' , &!
      form    = 'formatted', &!
      status  = 'unknown' &!
    )

    open( &!
      newunit = save_unit_error , &!
      file    = 'example/${SUBROUTINE_NAME}$_error.dat' , &!
      action  = 'write' , &!
      form    = 'formatted', &!
      status  = 'unknown' &!
    )


    do

      #:if DATA_TYPE == 'complex'
      read(unit=ref_unit, fmt=*, iostat=iostat) x%re, x%im, scipy_${P_N_SELECTABLE_INTERFACE}$(:)%re, scipy_${P_N_SELECTABLE_INTERFACE}$(:)%im
      #:elif DATA_TYPE == 'real'
      read(unit=ref_unit, fmt=*, iostat=iostat) x, scipy_${P_N_SELECTABLE_INTERFACE}$(:)
      #:endif

      if (iostat /= 0) exit


      actual_${P_N_SELECTABLE_INTERFACE}$(:) = ${P_N_SELECTABLE_INTERFACE}$(list_degree(:), x)

      error_${P_N_SELECTABLE_INTERFACE}$  (minval_degree:maxval_degree) = &!
      actual_${P_N_SELECTABLE_INTERFACE}$ (minval_degree:maxval_degree) - &!
      scipy_${P_N_SELECTABLE_INTERFACE}$  (minval_degree:maxval_degree)


      #:if DATA_TYPE == 'complex'
      write( save_unit_actual , * ) x%re, x%im, abs( actual_${P_N_SELECTABLE_INTERFACE}$ (:) )
      write( save_unit_error  , * ) x%re, x%im, abs( error_${P_N_SELECTABLE_INTERFACE}$  (:) )
      #:elif DATA_TYPE == 'real'
      write( save_unit_actual , * ) x, actual_${P_N_SELECTABLE_INTERFACE}$ (:)
      write( save_unit_error  , * ) x, error_${P_N_SELECTABLE_INTERFACE}$  (:)
      #:endif

    end do


    close( ref_unit         )
    close( save_unit_actual )
    close( save_unit_error  )

  end subroutine ${SUBROUTINE_NAME}$

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE
end program ${PROGRAM_NAME}$
