#! sampling the sample points using Fibonacci spiral
#:include '../src/common.fypp'
#:set NUM_POINTS = 2048
#:set GOLDEN_ANGLE = math.pi * (3 - math.sqrt(5))
#:for I in range(1, NUM_POINTS + 1)
#:set RAD = math.sqrt(I / NUM_POINTS)
#:set ARG = I * GOLDEN_ANGLE
#:set RE = RAD * math.cos(ARG)
#:set IM = RAD * math.sin(ARG)
#:set Z = RE + IM * 1j
#:set PLY_RE = ""
#:set PLY_IM = ""
#:for DEGREE in range( 0, (MAXVAL_DEGREE_INTERFACE + 1) )
#:set PLY = scipy.special.eval_legendre(DEGREE, Z)
#:set PLY_RE = PLY_RE + " " + str(PLY.real)
#:set PLY_IM = PLY_IM + " " + str(PLY.imag)
#:endfor
${RE}$ ${IM}$${PLY_RE}$${PLY_IM}$
#:endfor
