#:mute

#:set MAXVAL_DEGREE_INT32  = 15
#:set MAXVAL_DEGREE_real32 = 13
#:set MAXVAL_DEGREE_real64 = 27

#:if defined('WITH_REAL128')
  #:set MAXVAL_DEGREE_INT64     = 30
  #:set MAXVAL_DEGREE_INTERFACE = MAXVAL_DEGREE_INT64
  #:set REAL_KINDS              = [32, 64, 128]
#:else
  #:set MAXVAL_DEGREE_INT64     = MAXVAL_DEGREE_real64
  #:set MAXVAL_DEGREE_INTERFACE = MAXVAL_DEGREE_real64
  #:set REAL_KINDS              = [32, 64]
#:endif

#:set MODULE_NAME = 'legendre_polynomial_closed_form_fortran'

#:set CHECK_REAL_KIND = lambda real_kind, degree: (real_kind == 32 and degree <= MAXVAL_DEGREE_real32) or (real_kind == 64 and degree <= MAXVAL_DEGREE_real64) or (real_kind == 128)

#:set P_N_SELECTABLE_INTERFACE = 'p_n'

#:def P_N_SELECTABLE_FUNCTION(real_kind)
${P_N_SELECTABLE_INTERFACE}$_real${str(real_kind)}$
#:enddef P_N_SELECTABLE_FUNCTION

#:endmute
