#:mute

#:include 'common.fypp'

#:def DENOMINATOR_NAME(degree)
denominator_deg${str(degree).zfill(2)}$
#:enddef DENOMINATOR_NAME

#:def DENOMINATOR_VALUE(degree)
${2 ** degree}$
#:enddef DENOMINATOR_VALUE

#:def NUMERATOR_NAME(degree, j)
#:assert degree >= (2 * j)
numerator_deg${str(degree).zfill(2)}$_pow${str(degree - 2 * j).zfill(2)}$
#:enddef NUMERATOR_NAME

#:def NUMERATOR_VALUE(degree, j)
${(-1)**j * math.comb(degree, j) * math.comb( ( 2 * (degree - j) ), degree )}$
#:enddef NUMERATOR_VALUE

#:def P_N_FUNCTION(degree, data_type, real_kind)
${P_N_INTERFACE(degree)}$_${data_type}$${str(real_kind)}$
#:enddef P_N_FUNCTION

#:endmute
module ${MODULE_NAME}$
  !! Legendre polynomial evaluation for Fortran, via the closed-form expression.
  !! @note
  !! - \( P_n (x) \) is Legendre polynomial of degree \( n \)
  #:if defined('WITH_REAL128')
  !! - This module supports `real128`
  #:else
  !! - This module does NOT support `real128`
  #:endif
  !! @endnote

  use, intrinsic :: iso_fortran_env, only: int32
  use, intrinsic :: iso_fortran_env, only: int64
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor

  use, intrinsic :: ieee_arithmetic, only: ieee_signaling_nan
  use, intrinsic :: ieee_arithmetic, only: ieee_value



  implicit none



  private

  #:for DEGREE in range( 0, (MAXVAL_DEGREE_INTERFACE + 1) )
  public :: ${P_N_INTERFACE(DEGREE)}$
  #:endfor
  public :: ${P_N_SELECTABLE_INTERFACE}$



  #:for DEGREE in range( 2, (MAXVAL_DEGREE_INT64 + 1) )
  integer(int32), parameter :: ${DENOMINATOR_NAME(DEGREE)}$ = ${DENOMINATOR_VALUE(DEGREE).rjust(10)}$_int32 !! for \( P_{${str(DEGREE).rjust(2)}$} (x) \)
  #:endfor



  #:for DEGREE in range( 2, (MAXVAL_DEGREE_INT64 + 1) )
  #:for J in range( 0, (DEGREE//2 + 1) )
  integer(int${NUMERATOR_INT_KIND(DEGREE)}$), parameter :: ${NUMERATOR_NAME(DEGREE, J)}$ = ${NUMERATOR_VALUE(DEGREE, J).rjust(20)}$_int${NUMERATOR_INT_KIND(DEGREE)}$ !! for \( x^{${DEGREE - 2 * J}$} \) of \( P_{${DEGREE}$} (x) \)
  #:endfor

  #:endfor
  #! DEGREE

  #:for DEGREE in range( 0, (MAXVAL_DEGREE_INT64 + 1) )

  !> version: experimental
  #:if defined("WITH_REAL128")
  #:if DEGREE <= MAXVAL_DEGREE_REAL32
  !! \( P_{${DEGREE}$} (x) \) for `real32`, `real64` and `real128`
  #:elif DEGREE <= MAXVAL_DEGREE_REAL64
  !! \( P_{${DEGREE}$} (x) \) for `real64` and `real128`
  #:else
  !! \( P_{${DEGREE}$} (x) \) for `real128` only
  #:endif
  #:else
  #:if DEGREE <= MAXVAL_DEGREE_REAL32
  !! \( P_{${DEGREE}$} (x) \) for `real32` and `real64`
  #:elif DEGREE <= MAXVAL_DEGREE_REAL64
  !! \( P_{${DEGREE}$} (x) \) for `real64` only
  #:endif
  #:endif
  #:set INTERFACE_NAME = P_N_INTERFACE(DEGREE)
  interface ${INTERFACE_NAME}$
    #:for DATA_TYPE in DATA_TYPES
    #:for REAL_KIND in REAL_KINDS
    #:if CHECK_REAL_KIND(REAL_KIND, DEGREE)
    module procedure ${P_N_FUNCTION(DEGREE, DATA_TYPE, REAL_KIND)}$
    #:endif
    #:endfor
    #:endfor
  end interface ${INTERFACE_NAME}$
  #:del INTERFACE_NAME

  #:endfor
  #! DEGREE

  !> version: experimental
  !! $$
  !! P_n (x) \ ( n = 0 , 1, \dots , N ),\ 
  !! N =
  !! \begin{cases}
  #:if defined("WITH_REAL128")
  !! ${MAXVAL_DEGREE_REAL( 32)}$ & \text{for real32} \\
  !! ${MAXVAL_DEGREE_REAL( 64)}$ & \text{for real64} \\
  !! ${MAXVAL_DEGREE_REAL(128)}$ & \text{for real128}
  #:else
  !! ${MAXVAL_DEGREE_REAL(32)}$ & \text{for real32} \\
  !! ${MAXVAL_DEGREE_REAL(64)}$ & \text{for real64}
  #:endif
  !! \end{cases}
  !! $$
  interface ${P_N_SELECTABLE_INTERFACE}$
    #:for REAL_KIND in REAL_KINDS
    module procedure ${P_N_SELECTABLE_FUNCTION(REAL_KIND)}$
    #:endfor
  end interface ${P_N_SELECTABLE_INTERFACE}$


  contains

  #! REAL_KIND

  #:for DEGREE in range( 0, (MAXVAL_DEGREE_INT64 + 1) )

  #:for DATA_TYPE in DATA_TYPES
  #:for REAL_KIND in REAL_KINDS

  #:if CHECK_REAL_KIND(REAL_KIND, DEGREE)
  #:set FUNCTION_NAME = P_N_FUNCTION(DEGREE, DATA_TYPE, REAL_KIND)
  ${DATA_TYPE}$(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)
    !! version: experimental
    !! \( P_{${DEGREE}$} (x) \) for `${DATA_TYPE}$(real${REAL_KIND}$)`

    ${DATA_TYPE}$(real${REAL_KIND}$), intent(in) :: x

    #:if DEGREE == 0
    ${FUNCTION_NAME}$ = real(1, kind=kind(x))
    #:elif DEGREE == 1
    ${FUNCTION_NAME}$ = x
    #:elif DEGREE == 2
    ${FUNCTION_NAME}$ = (${NUMERATOR_NAME(DEGREE, 0)}$ * x * x + ${NUMERATOR_NAME(DEGREE, 1)}$) / ${DENOMINATOR_NAME(DEGREE)}$
    #:elif DEGREE == 3
    ${FUNCTION_NAME}$ = (${NUMERATOR_NAME(DEGREE, 0)}$ * x * x + ${NUMERATOR_NAME(DEGREE, 1)}$) * x / ${DENOMINATOR_NAME(DEGREE)}$
    #:else

    ${DATA_TYPE}$(real${REAL_KIND}$) :: x2


    x2 = x * x

    ${FUNCTION_NAME}$ = ${NUMERATOR_NAME(DEGREE, 1)}$ + x2 * ${NUMERATOR_NAME(DEGREE, 0)}$
    #:for J in range( 2, (DEGREE//2 + 1) )
    ${FUNCTION_NAME}$ = ${NUMERATOR_NAME(DEGREE, J)}$ + x2 * ${FUNCTION_NAME}$
    #:endfor

    ${FUNCTION_NAME}$ = ${FUNCTION_NAME}$#{if DEGREE % 2 != 0}# * x#{endif}# / ${DENOMINATOR_NAME(DEGREE)}$
    #:endif

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME
  #:endif

  #:endfor
  #! REAL_KIND
  #:endfor
  #! DATA_TYPE

  #:endfor
  #! DEGREE

  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = P_N_SELECTABLE_FUNCTION(REAL_KIND)
  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(degree, x)
    !! version: experimental
    !! \( P_n (x) \ ( n = 0 , 1, \dots , ${MAXVAL_DEGREE_REAL(REAL_KIND)}$ ) \) for `real${REAL_KIND}$`

    integer(int32), intent(in) :: degree

    real(real${REAL_KIND}$), intent(in) :: x


    select case (degree)

      #:for DEGREE in range(0, MAXVAL_DEGREE_REAL(REAL_KIND) + 1)
      case ( ${str(DEGREE).rjust(2)}$_int32 ); ${FUNCTION_NAME}$ = ${P_N_INTERFACE(DEGREE)}$(x)
      #:endfor

      case default; ${FUNCTION_NAME}$ = ieee_value(x, ieee_signaling_nan)

    end select

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND
end module ${MODULE_NAME}$
