#:mute

#:set MAXVAL_DEGREE_INT32  = 15
#:set MAXVAL_DEGREE_real32 = 13
#:set MAXVAL_DEGREE_real64 = 27

#:if defined('WITH_REAL128')
  #:set MAXVAL_DEGREE_INT64     = 30
  #:set MAXVAL_DEGREE_INTERFACE = MAXVAL_DEGREE_INT64
  #:set REAL_KINDS              = [32, 64, 128]
#:else
  #:set MAXVAL_DEGREE_INT64     = MAXVAL_DEGREE_real64
  #:set MAXVAL_DEGREE_INTERFACE = MAXVAL_DEGREE_real64
  #:set REAL_KINDS              = [32, 64]
#:endif

#:set MODULE_NAME = 'legendre_polynomial_closed_form_fortran'

#:set CHECK_REAL_KIND = lambda real_kind, degree: (real_kind == 32 and degree <= MAXVAL_DEGREE_real32) or (real_kind == 64 and degree <= MAXVAL_DEGREE_real64) or (real_kind == 128)

#:def DENOMINATOR_NAME(degree)
denominator_deg${str(degree).zfill(2)}$
#:enddef DENOMINATOR_NAME

#:def DENOMINATOR_VALUE(degree)
${2 ** degree}$
#:enddef DENOMINATOR_VALUE

#:def NUMERATOR_INT_KIND(degree)
#:if degree <= MAXVAL_DEGREE_INT32
32
#:elif degree <= MAXVAL_DEGREE_INT64
64
#:else
#:stop '`degree` must be less than {}.'.format(MAXVAL_DEGREE_INT64 + 1)
#:endif
#:enddef NUMERATOR_INT_KIND

#:def NUMERATOR_NAME(degree, j)
#:assert degree >= (2 * j)
numerator_deg${str(degree).zfill(2)}$_pow${str(degree - 2 * j).zfill(2)}$
#:enddef NUMERATOR_NAME

#:def NUMERATOR_VALUE(degree, j)
${(-1)**j * math.comb(degree, j) * math.comb( ( 2 * (degree - j) ), degree )}$
#:enddef NUMERATOR_VALUE

#:def P_N(degree)
p_${str(degree).zfill(2)}$
#:enddef P_N

#:def P_N_REAL(degree, real_kind)
${P_N(degree)}$_real${str(real_kind)}$
#:enddef P_N_REAL

#:endmute
module ${MODULE_NAME}$

  use, intrinsic :: iso_fortran_env, only: int32
  use, intrinsic :: iso_fortran_env, only: int64
  #:for REAL_KIND in REAL_KINDS
  use, intrinsic :: iso_fortran_env, only: real${REAL_KIND}$
  #:endfor



  implicit none



  private

  #:for DEGREE in range( 0, (MAXVAL_DEGREE_INTERFACE + 1) )
  public :: ${P_N(DEGREE)}$
  #:endfor



  #:for DEGREE in range( 2, (MAXVAL_DEGREE_INT64 + 1) )
  integer(int32), parameter :: ${DENOMINATOR_NAME(DEGREE)}$ = ${DENOMINATOR_VALUE(DEGREE).rjust(10)}$_int32
  #:endfor



  #:for DEGREE in range( 2, (MAXVAL_DEGREE_INT64 + 1) )
  #:for J in range( 0, (DEGREE//2 + 1) )
  integer(int${NUMERATOR_INT_KIND(DEGREE)}$), parameter :: ${NUMERATOR_NAME(DEGREE, J)}$ = ${NUMERATOR_VALUE(DEGREE, J).rjust(20)}$_int${NUMERATOR_INT_KIND(DEGREE)}$
  #:endfor

  #:endfor
  #! DEGREE

  #:for DEGREE in range( 0, (MAXVAL_DEGREE_INT64 + 1) )

  #:set INTERFACE_NAME = P_N(DEGREE)
  interface ${INTERFACE_NAME}$
    #:for REAL_KIND in REAL_KINDS
    #:if CHECK_REAL_KIND(REAL_KIND, DEGREE)
    module procedure ${P_N_REAL(DEGREE, REAL_KIND)}$
    #:endif
    #:endfor
  end interface ${INTERFACE_NAME}$
  #:del INTERFACE_NAME

  #:endfor
  #! DEGREE


  contains


  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = P_N_REAL(0, REAL_KIND)
  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x

    ${FUNCTION_NAME}$ = real(1, kind=kind(x))

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND


  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = P_N_REAL(1, REAL_KIND)
  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x

    ${FUNCTION_NAME}$ = x

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND


  #:set DEGREE = 2
  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = P_N_REAL(DEGREE, REAL_KIND)
  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x

    ${FUNCTION_NAME}$ = (${NUMERATOR_NAME(DEGREE, 0)}$ * x * x + ${NUMERATOR_NAME(DEGREE, 1)}$) / ${DENOMINATOR_NAME(DEGREE)}$

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND
  #:del DEGREE


  #:set DEGREE = 3
  #:for REAL_KIND in REAL_KINDS

  #:set FUNCTION_NAME = P_N_REAL(DEGREE, REAL_KIND)
  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x

    ${FUNCTION_NAME}$ = (${NUMERATOR_NAME(DEGREE, 0)}$ * x * x + ${NUMERATOR_NAME(DEGREE, 1)}$) * x / ${DENOMINATOR_NAME(DEGREE)}$

  end function ${FUNCTION_NAME}$
  #:del FUNCTION_NAME

  #:endfor
  #! REAL_KIND
  #:del DEGREE

  #:for DEGREE in range( 4, (MAXVAL_DEGREE_INT64 + 1) )

  #:for REAL_KIND in REAL_KINDS
  #:if CHECK_REAL_KIND(REAL_KIND, DEGREE)
  #:set FUNCTION_NAME = P_N_REAL(DEGREE, REAL_KIND)

  real(real${REAL_KIND}$) elemental function ${FUNCTION_NAME}$(x)

    real(real${REAL_KIND}$), intent(in) :: x


    real(real${REAL_KIND}$) :: x2


    x2 = x * x

    ${FUNCTION_NAME}$ = ${NUMERATOR_NAME(DEGREE, 1)}$ + x2 * ${NUMERATOR_NAME(DEGREE, 0)}$
    #:for J in range( 2, (DEGREE//2 + 1) )
    ${FUNCTION_NAME}$ = ${NUMERATOR_NAME(DEGREE, J)}$ + x2 * ${FUNCTION_NAME}$
    #:endfor

    ${FUNCTION_NAME}$ = ${FUNCTION_NAME}$#{if DEGREE % 2 != 0}# * x#{endif}# / ${DENOMINATOR_NAME(DEGREE)}$

  end function ${FUNCTION_NAME}$

  #:del FUNCTION_NAME
  #:endif
  #:endfor
  #! REAL_KIND

  #:endfor
  #! DEGREE
end module ${MODULE_NAME}$
